// client/src/components/RestaurantCard.vue
<script setup lang="ts">
import { defineProps } from 'vue'
import ClosedBadge from './ClosedBadge.vue'
import OpenBadge from './OpenBadge.vue'
import type { Restaurant } from '@/types'

const props = defineProps<{ restaurant: Restaurant }>()
</script>

<template>
  <div class="bg-base-200 shadow rounded-xl p-4">
    <h2 class="text-xl font-bold">{{ props.restaurant.name }}</h2>
    <hr />
    <span>Rating: {{ props.restaurant.rating }}</span>
    <hr />
    <hr />
    <a :href="props.restaurant.url">Link</a>
    <hr />
    <OpenBadge v-if="props.restaurant.openNow" />
    <ClosedBadge v-else />
  </div>
</template>

// client/src/components/restaurant-card/RestaurantCard.tsx
import { Restaurant } from "../../types";
import "./styles.css";

interface RestaurantCardProps {
  restaurant: Restaurant;
}

export default function RestaurantCard({ restaurant }: RestaurantCardProps) {
  return (
    <div className="card">
      <h3>{restaurant.name}</h3>
      <p>Rating: {restaurant.rating}</p>
      <p>{restaurant.openNow ? "Currently Open" : "Not open yet"}</p>
      <p className="address">{restaurant.address}</p>
      <p>
        <a href={restaurant.url}>Link</a>
      </p>
    </div>
  );
}
